### ISSUE TITLE
GPIO pin export causing existing pin state to bounce.

### ISSUE THREAD

**Issue by savageautomate** [Pi4J/pi4j-v1#136]
GPIO pin export causing existing pin state to bounce from a preexisting HIGH state to a short duration LOW state and then back to HIGH state.

See this thread for more details.
https://groups.google.com/d/msgid/pi4j/21b2e528-39e1-4718-b574-c0b262b22698%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by cletusdsouza** [comment]
Hi, I'm having an opposite problem...  I start off with provisioning the pin to LOW, then to open the garage door, I pulse the pin for half a second.  However, if the pi reboots or unexpectedly looses power, my relay goes back to HIGH sending the garage door wide open :-(

Initialization code:
static final GpioPinDigitalOutput leftDoorPin = GpioFactory.getInstance().provisionDigitalOutputPin(RaspiPin.GPIO_04, "Left_Garage_Door", PinState.LOW);
leftDoorPin.setShutdownOptions(true, PinState.LOW, PinPullResistance.OFF);

To open:
leftDoorPin.pulse(500, true); 
leftDoorPin.setState(PinState.LOW);
leftDoorPin.setPullResistance(PinPullResistance.OFF);

I need to start at the LOW pin state otherwise my wall switch (that's where the relay plugs into) doesn't work.  Can you help or suggest how to keep the wall switch working and keep the relay from switching when the pi reboots or looses power?

I'm a complete noob when it comes to GPIO and relays, so any help you can provide is greatly appreciated!  For reference, I'm using the following for the physical wiring - http://itsbrent.net/2013/03/hacking-my-garage-with-a-raspberry-pi/ but I'm not using that code.  I've written a pi4j app to interface with GPIO.
