### ISSUE TITLE
Add support for a blocking pulse on  GPIO output pins

### ISSUE THREAD

**Issue by savageautomate** [Pi4J/pi4j-v1#22]
Add support for a optional GPIO pin pulse(duration) that will block the caller's thread until the pulse instruction and duration has completed.  

The current pulse is implemented as a background task that is carried out in a worker thread pool.

**Comment by savageautomate** [comment]
Added in 0.0.4-SNAPSHOT to GpioPinDigitalOutput interface.

```
void pulse(long duration, boolean blocking);    
void pulse(long duration, PinState pulseState, boolean blocking);
```

Set the blocking argument to "true" to invoke a blocking pulse.

**Comment by kermitas** [comment]
If I can advice something: creating pulse taks can retrun Future.
That's all.

**Comment by savageautomate** [comment]
I like that idea for the normal pulse.  Do you think a blocking pulse should be entirely separate methods?

**Comment by kermitas** [comment]
First idea:
- normal (non blocking) pulse returns Future, you can use it or not,

```
ScheduledFuture pulse(long duration);
```
- your new mode (blocking) just use previous method and blocks on returned ScheduledFuture.get() method

```
ScheduledFuture pulse(long duration , boolean blocking);
```

Second idea:
- there should be just one main method

```
ScheduledFuture pulse(long duration, PinState pulseState, boolean blocking);
```
- and few overloading methods that works just like today (to keep backward compability)

Of course you can always break backward compability and remove old methods.
I think second idea is better.

**Comment by savageautomate** [comment]
I think I implemented it more like your second suggestion.  There is one method where all the work resides and then a series of overloaded methods for user convenience that all call into the main method.  Blocking pulse invocations simply return a null Future object.   

Check out the change and let me know what you think:
https://github.com/Pi4J/pi4j/commit/a677bf6a3d5e2276002572e1bd0756fba2b00be7

**Comment by kermitas** [comment]
Second suggestion is better from programming point of view.

Why return null, write new documentation and remember that blocing methods return null that can put somebody into troubles? Blocing metods can be void type. If not just return old (used) ScheduledFuture object and don't risk that somebody will get NullPointerException.

https://github.com/Pi4J/pi4j/commit/a677bf6a3d5e2276002572e1bd0756fba2b00be7 Looks very nice. I didn't find any use of "boolean blocking" but as I understand it is work-in-progress version :).

And one more thing. If duration is <=0 then you are returning null. Ok, I understand that but it looks like old fashion C/C++ times. In Java world if arguments passed to method are not right you should throw exception (for example llegalArgumentException).

I also saw `scheduledExecutorService.shutdown();` - as you rembemer. If you are creator of this thread pool then it is no problem - you are this threads pool manager. But in case thread pool was passed from external world (for example during initialization of library) then better wrap it into wrapper that will does not allow to do shutdown().
After few minutes of thinking: you know what is the best solution in this situation? Always request to pass external thread pool to main construcotr or main factory method of your library. You always will use externally passed thread pool so you will never need to shut it down (because you will never be manager/creator of this thead pool).

Sorry for my english.
(Of course do like you think that is better. I don't want you to get into troubles and have to replace a tons of code now. You can always create issue and introduce those changes in future.)

**Comment by savageautomate** [comment]
I guess that checkin link did not show the full changes to the code.  Probably because it was done in multiple checkins.  To see the full change use these links:

https://github.com/Pi4J/pi4j/blob/a677bf6a3d5e2276002572e1bd0756fba2b00be7/pi4j-core/src/main/java/com/pi4j/io/gpio/GpioPinDigitalOutput.java#L47

https://github.com/Pi4J/pi4j/blob/a677bf6a3d5e2276002572e1bd0756fba2b00be7/pi4j-core/src/main/java/com/pi4j/io/gpio/impl/GpioPinImpl.java#L249

I did have a validation check for duration first thing; you just could not see in via that previous link:

```
    // validate duration argument
    if(duration <= 0)
        throw new IllegalArgumentException("Pulse duration must be greater than 0 milliseconds.");
```

The rework of the scheduled executor allowing someone to inject and manage their own is planned in 0.0.5.
https://github.com/Pi4J/pi4j/issues/10

As for the blocking methods, the ones with the optional boolean blocking argument; are you saying that these should be void return types?  I was just trying to keep all the pulse methods close to the same signature.   Thoughts?

**Comment by kermitas** [comment]
Ok, all looks very good! :)

"I was just trying to keep all the pulse methods close to the same signature. Thoughts?" - no, no thoughts. Exacly, keep all methods with the same signature.

**Comment by savageautomate** [comment]
Well, I am still returning nulls for blocking calls.  So do you think this should change?  It is possible to create a used Future and return that instead?

**Comment by kermitas** [comment]
Yes, I saw those nulls.

I think you should return 'empty' Future.... but on the other site we are working on limited device (not much RAM, not much CPU) so it worth to save ram/cpu/gc. Now I think you should return null as you do now.

**Comment by savageautomate** [comment]
Thanks for all your feedback, I'm calling this feature done for the time being :-)
