### ISSUE TITLE
Java 7 feature request, java.lang.AutoCloseable.

### ISSUE THREAD

**Issue by mtstorm** [Pi4J/pi4j-v1#233]
Is it possible to let the interface com.pi4j.io.serial.Serial extend java.lang.AutoCloseable since Pi4J is using Java 7? This will save me a ton of code in our application. The solution is realy easy, just modifiy the interface description.

Better solution is that you can pick java.io.Closeable since the exceptions for the method close matches. If people are using Java 6 or 5 the can also still use it. 

public interface Serial extends SerialDataReader, SerialDataWriter, AutoCloseable  {
    /**
     \* This method is called to close a currently open open serial port.
     *
     \* @throws IllegalStateException thrown if the serial port is not already open.
     \* @throws IOException thrown on any error.
     */
    public void close() throws IllegalStateException, IOException;
}

If you wish, I can help, its a minor change that saves a lot of code for Java 7 developers using try with resources statement.

**Comment by savageautomate** [comment]
I have implemented `AutoCloseable` as you suggested. (in the _develop_ branch) 

I could not implement `Closeable` instead because it requires that the `close()` method be idempotent.  The current implementation of `close()` will throw an `IllegalStateException` if invoked when the serial port is already closed.

Please let me know if there is anything else needed. 
Thanks, Robert
