### ISSUE TITLE
Snapshot 1.1 PCA9685GpioServoExample ArrayIndexOutOfBoundsException: 15

### ISSUE THREAD

**Issue by Dorphus** [Pi4J/pi4j-v1#240]
I manually updated from the latest available version 1.0.1 from pi4j to the snapshot version 1.1 to solve the BigDecimal issue, but I keep running in new problems with the ExampleCode from Pi4j.
I've already fixed the try catch issue of the I2CBus, but I have no idea how to fix the ArrayIndexOutOfBoundsException.

I already read the issue discussing this error for the 1.0 version and it was stated that this was fixed by making a dynamic array in 1.1 so my guess is that the ExampleCode is outdated and doesn't initialize the dynamic big enough. Esepcially since it's index 15 that cannot be approached.

Is there a fix for this?

Thanks in advance

**Comment by savageautomate** [comment]
It turned out that the PCA9685GpioProvider has it's own (_statically allocated_) pin cache array and it was allocating 15 instead of 16 which did not leave enough room for pin index 15 since they start at 0.  

I don't have the hardware to test this fix, but I have published a new build of 1.1-SNAPSHOT that does include this attempted fix.  

Please let me know if you have any further trouble with this Exception.

Thanks, Robert
