### ISSUE TITLE
Are pin shutdown states a consideration if app never shuts off?

### ISSUE THREAD

**Issue by zharvey-welltok** [Pi4J/pi4j-v1#365]
I'm looking at running a JVM app on a Raspberry Pi (RPi), and will be using [pi4j]() to communicate with the GPIO pins from the Java layer.

This app will be configured to be a startup service (hence it starts up as soon as the RPi gets powered on, and the OS allows it to). Unless there are any more graceful solutions out there, my plan is to just shut everything down **un-gracefully**; that is, kill the power to the RPi and everything shuts off immediately, just like what used to happen when we all had big desktop towers :-)

**So for one, I'm worried that this will cause Raspbian (the OS), maybe even Java to be terminated in a wonky/error state.** But I'm not sure what else I can do to get it to shutdown gracefully: the app needs to run so long as the OS is running and power is being supplied to it. I wish there was a way to engage a shutdown hook here for a graceful exit, but if you kill power to the machine itself, there's nothig Java can do to help you.

I noticed that pi4j has the concepts of pin "shutdown states" as well as a core `shutdown()` method built into it:

    GpioController gpio = GpioFactory.getInstance();
    GpioPinDigitalOutput pin = gpio.provisionDigitalOutputPin(RaspiPin.GPIO_01, "MyLED", PinState.HIGH);
    pin.setShutdownOptions(true, PinState.LOW);
    gpio.shutdown();

And so my concerns:

* If I already know that my app will be "shutting down" whenever the power supplied is killed, do I even need to worry about pin shutdown states or this `shutdown()` method? Will state somehow be affected the next time the app runs?
* Is my "shutting down by killing the power" approach going to cause other problems for me, or is Raspbian/pi4j resilient to this sort of thing?

**Comment by savageautomate** [comment]
> If I already know that my app will be "shutting down" whenever the power supplied is killed, do I even need to worry about pin shutdown states or this shutdown() method? Will state somehow be affected the next time the app runs?

Nope.  I believe that the RPi will reset all pin states to a known default (ie safe) state at boot time.  Your app must re-configure all the pins that you are using each time your app starts up.

**(UPDATE: FYI, your hardware connected to GPIO pins needs to be aware of and safely accommodate GPIO pin state change on at system power-down and reboot.)**
 
>  Is my "shutting down by killing the power" approach going to cause other problems for me, or is Raspbian/pi4j resilient to this sort of thing?

I think most people would say its a bad idea to just pull the power -- mainly because of the potential for SD card corruption.  However, that's how I usually turn mine off.  No, it should not impact Pi4J in any way as it does not persist any state between runtime instances.  

You may want to look into a service layer wrapper for your app.  Like : **https://commons.apache.org/proper/commons-daemon/jsvc.html**

I think you can implement hooks to perform any necessary shutdown actions is a more graceful manner.
https://wiki.apache.org/commons/Daemon

Of course this service wrapper only helps on graceful/orderly system shutdowns when a proper shutdown instruction has been issued to the OS.  It's not going to matter is the system is simply unplugged.  

Good Luck, Robert
