### ISSUE TITLE
SPI wiringPiSPISetupMode returns wrong file descriptor

### ISSUE THREAD

**Issue by amcelroy** [Pi4J/pi4j-v1#377]
Howdy,

I'm using the latest 1.2-SNAPSHOT with the latest (10-14-2017) firmware and update. When using wiringPiSPISetupMode, it is always returning a file descriptor of 331, which, when used with wiringPiSPIDataRW causes an error.

The temporary solution is to use 0 as the file descriptor.

**Comment by savageautomate** [comment]
Reviewing _this issue prior to the v1.3 release._

I was not able to duplicate the error.  It was most likely due to an older version of WiringPi.
I have tested using latest **Pi4J v1.3-SNAPSHOT** on a RPi 4B with latest *unofficial* **WiringPi v2.60**

See here for latest WiringPi installation: https://pi4j.com/1.3/install.html#WiringPi_Native_Library

Below is the code snippet I used to test with:

```java
// setup SPI for communication
int fd = Spi.wiringPiSPISetupMode(0, 10000000, SpiMode.MODE_0.getMode());
if (fd <= -1) {
    System.out.println(" ==>> SPI SETUP FAILED");
    return;
}
System.out.println(" ==>> SPI SETUP MODE FD=" + fd);
```

The resulting output was: ` ==>> SPI SETUP MODE FD=14`

Closed.
