### ISSUE TITLE
Dependency Information gradle entry seems wrong

### ISSUE THREAD

**Issue by skim1420** [Pi4J/pi4j-v1#477]
The [Dependency Information](https://pi4j.com/1.2/dependency-info.html) page has an entry for gradle that points to `compile 'com.pi4j:pi4j-parent:1.2'`, which seems like a parent project ([has no published jars](https://repo1.maven.org/maven2/com/pi4j/pi4j-parent/1.2/)), and didn't work for me. Pointing to `com.pi4j:pi4j-core:1.2` worked for me. Should this page be updated accordingly?

**Comment by savageautomate** [comment]
**Fixed in upcoming v1.3 release**
Thanks for pointing this out.  (_I realize it was a year ago now._)

This page is an artifact of the Maven site plugin used during our build and release process.  You are correct the dependency info is wrong.  I'll have to look and see if wee can change which artifact IS its populating to that page.
