### ISSUE TITLE
New Wiring version for 512 Support

### ISSUE THREAD

**Issue by fizou** [Pi4J/pi4j-v1#5]
I understand that Wiring Pi is embedded the Pi4J native library in .so.

I've got a raspi 512mo Revision 000f.

It seems "embedded Wiring version" doesn't detect that revision.

Wich version of Wiring is embeded in PI4j ? 

Do you expect release a new version with the last Wiring framework ? or is there a procedure for generate .so with the last version ?

Thx for your response?

**Comment by geoffgomez** [comment]
I think I'm hitting a similar problem, I'm trying to use Pins 8 & 9 as general GPIO pins. Was all working o.k. until I upgraded the firmware to allow me to see the full 512M. Since then PI4J cannot seem to do anything with them.
I am still able to use the wiringPi gpio program to read the pin states. Could this simply need a rebuild of the embedded library?

**Comment by Un4Cn** [comment]
I'm also having a problem using pins 2,8,9 and I also have Model B, rev 2.0 with latest firmware. Pi4J is unable to communicate with pins 2,8,9 on hardware level, although the WiringPi gpio utility communicates well with these pins. All other pins work well with Pi4J too. For details read this post on the forum:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=34&t=22882

**Comment by geoffgomez** [comment]
I gave it a go and downloaded the latest source packages for both wiringPi and pi4j and building both from scratch (in that order). I'm a complete novice with Maven so I found the pi4j challenging and have probably made a right hash of it but got with a working library in the end. 

If you do decide to build yourself be aware that the latest wiringPi does not seem to create /usr/local/lib/libwiringPi.a which pi4j relies on. I created a symbolic link to libwiringPi.so.1.0 which allowed it to build (presumably correctly as it works). This is probably a bit iffy but has worked for me.

Hope this helps.

**Comment by Un4Cn** [comment]
Wow, so it's fixed? In that case I might decide to do a build from the latest sources myself, although I'm probably even more novice than you are :)

**Comment by savageautomate** [comment]
Hi Guys, I don't have a new 512 MB model to test with, but it sounds like from the comments above that Pi4J needs to be compiled with a newer version of WiringPi.   I will be happy to do this and post an updated version for download; however, it will take be a few days to get to it.  Probably Monday/Tuesday.  

Building the Pi4J-native project can be tricky because it is technically using SSH to compile the project against the WiringPi sources on a physical Pi hardware.  I would like to get to the point where I have cross-compiling working in the Maven build, but just have not had the time to make that happen yet.

**Comment by fizou** [comment]
Ok nice, I can test it before release if you need...

**Comment by Un4Cn** [comment]
Same here, I'll gladly test it :)

**Comment by savageautomate** [comment]
Great!  I will update this thread when it is available for testing.  Thanks!

**Comment by savageautomate** [comment]
It looks like the latest wiringPi Makefile no longer includes compiling and linking the libwiringPi.a static library.  I have sent an email to Gordon to see if that was intentional or if maybe support could be added back to the makefile as a separate build target.  

I am looking to fully automate the pi4j-native Maven project to include pulling the latest wiringPi sources and building the wiringPi library as part of the pi4j-native project build.  This will help ensure that as new versions of Pi4J are produced, they are always getting compiled against the latest wiringPi library.

In the meantime, I will go ahead and make the manual edits to the wiringPi Makefile to generate the libwiringPi.a static library so I can push out an updated version of Pi4J.

**Comment by savageautomate** [comment]
The new 0.0.4-SNAPSHOT build is available for testing.  This build is compiled against the latest wiringPi sources.

You can download it from the Maven repository here:
https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-core/0.0.4-SNAPSHOT/

Please report success or any remaining open defects/issues.

**Comment by Un4Cn** [comment]
I can confirm, Pi4J is now able to properly communicate with all the 17 programmable GPIO pins on my Pi board (model B, revision 2.0)! Thank you, Robert!

**Comment by savageautomate** [comment]
Great news.  

I also spoke with Gordon and he will add support back in to the wiringPi makefile to include compiling the static library.  After this is ready, I will update the pi4j-native project to additionally download and build the wiringPi sources as part of the maven build to ensure that pi4j is always using the latest wiringPi sources.

**Comment by gorstj** [comment]
Do you know which pins are available for use with the 512mb pi and snapshot 0.0.2?
I am currently using pin 8 and 26 (GPIO 14 and 7) but am having difficulty with lots of the others.

**Comment by Un4Cn** [comment]
Hi!

Unfortunately I don't know, because I started out with Pi4J snapshot 0.0.3, I have never used 0.0.2.
But why don't you upgrade to the latest one (0.0.4), which works well with all the programmable GPIO pins (0..16)?
https://oss.sonatype.org/content/groups/public/com/pi4j/pi4j-core/0.0.4-SNAPSHOT/

If you decide to upgrade, be aware that it's built with the latest Java version, and you'll need to use the latest JDK in you application.
Andras

**Comment by savageautomate** [comment]
I don't think 0.0.2 is built with the version of WiringPi that deals with the pin differences on the newer firmware/hardware.  For the best results using a 512 Pi, please use the 0.0.4 development build that Andras suggested.  

Thanks, Robert

**Comment by savageautomate** [comment]
The wiringPi project makefile has been updated to support building the native static library again.  
I have also now updated the pi4j-native project to automatically pull and compile the latest wiringPi sources as part of the pi4j-native maven build process.  This hopefully will ensure that we always are getting the latest wiringPi when Pi4j is released.
